### PR TITLE
Added Carthage support

### PR DESCRIPTION
**Pull request by colemancda**

### CODE REVIEW

**Comment by Joannis** [comment]
I'm assuming this is still in-progress, correct?

**Comment by colemancda** [comment]
I thought it was finished, but I realized the `.xcproj` was being ignored.

**Comment by Joannis** [comment]
What is the motive for adding Carthage support? Doesn't SPM suffice?

**Comment by colemancda** [comment]
Not for iOS

	Coleman,

**Comment by Joannis** [comment]
@colemancda I can see why that would be useful. I'll be testing your commit over the course of the next few hours.

**Comment by Joannis** [comment]
I'm unable to run BSON on iOS due to `image not found`. I'll hold this until I can get it working

**Pull request merged**
